# Generated by Django 3.0.3 on 2020-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20200224_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ManyToManyField(to='pictures.Album'),
        ),
    ]
