# Generated by Django 3.0.3 on 2020-02-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_picture_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
