# Generated by Django 3.0.3 on 2020-02-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_remove_picture_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
